### ISSUE TITLE
PHP7 - Declaration of Upwork\API\Routers\Snapshot::get($company, $username, $ts) should be compatible with Upwork\API\Client::get($url, $params = Array)

### ISSUE THREAD

**Issue by alenn-m** [upwork/php-upwork#11]
When I run this code:
`$snapshots = new Snapshot($client);`
I get this error:
`Declaration of Upwork\API\Routers\Snapshot::get($company, $username, $ts) should be compatible with Upwork\API\Client::get($url, $params = Array)`

Other API works fine, I found issues only with `Snapshot` class

**Comment by alenn-m** [comment]
Same issue with this:
`$workdiary = new Workdiary($client);`

**Comment by mnovozhylov** [comment]
@alenn-m , sorry, I don't follow you - Client::get requires 1 parameter, the Snapshot::get sends a required parameter. Same with Workdiary API.

**Comment by alenn-m** [comment]
Yes, but both Snapshot and Workdiary extends Client class, and inside Client there is `get($url, $params = array())` method, but in Snapshot and Workdiary there is `get($company, $username, $ts)` and those methods must be compatible (with same params) in PHP 7

**Comment by mnovozhylov** [comment]
- second parameter is optional
- the requirements of php7 were not tested with this library
