### ISSUE TITLE
Oauth included library exceptions. 

### ISSUE THREAD

**Issue by vg-github** [upwork/php-upwork#12]
I'm getting these two erros while trying to connect with my API key & secret via the shipped oauth component:

`Fatal error: Uncaught exception 'OAuthException2' with message 'Unexpected result from the server "https://www.upwork.com/api/auth/v1/oauth/token/access" (401) while requesting an access token' in /home/ubuntu/workspace/vendor/upwork/php-upwork/vendor-src/oauth-php/library/OAuthRequester.php on line 258`

`OAuthException2: Unexpected result from the server "https://www.upwork.com/api/auth/v1/oauth/token/access" (401) while requesting an access token in /home/ubuntu/workspace/vendor/upwork/php-upwork/vendor-src/oauth-php/library/OAuthRequester.php on line 258`

Am I doing anything wrong?

This is the debug output:

```
> preparing Client.
> starting Upwork\API\AuthTypes\AbstractOAuth authentication.
> authing Client.
> running auth process in Upwork\API\AuthTypes\AbstractOAuth.
> query request token from server.
> get OAuth instance.
> create full url, based on global constant.
> url, dump: 'https://www.upwork.com/api/auth/v1/oauth/token/request'.
> create full url, based on global constant.
> url, dump: 'https://www.upwork.com/api/auth/v1/oauth/token/access'.
> got request token info, dump: array (
  'authorize_uri' => '/services/api/auth',
  'token' => '[REMOVED]',
  'token_secret' => '[REMOVED]',
).
> create full url, based on global constant.
> url, dump: 'https://www.upwork.com/services/api/auth'.
> found [nonweb] mode, need to autorize application manually.
> requesting access token.
> get OAuth instance.
> create full url, based on global constant.
> url, dump: 'https://www.upwork.com/api/auth/v1/oauth/token/request'.
> create full url, based on global constant.
> url, dump: 'https://www.upwork.com/api/auth/v1/oauth/token/access'.
```

Any feedback would be helpful. 

Many thanks,
VG

**Comment by mnovozhylov** [comment]
Please, check the readme and configure your application properly.
