### ISSUE TITLE
Documentation woefully simplified/incomplete

### ISSUE THREAD

**Issue by reedy** [upwork/php-upwork#17]
https://github.com/upwork/php-upwork/blob/master/README.md#installation-by-downloading-sources

Says copy https://github.com/upwork/php-upwork/blob/master/example/console.php to myapp.php

Then "open myapp.php and type the consumerKey and consumerSecret that you previously got from the API Center."

This isn't very helpful. As this point, you'll need to take the malformed URL (see also #16 ) and put it into a web browser, login, and then give the code back......

But then it's all kinda useless trying to use the upwork api via a command line, if it needs interactivity. You can't run it via cron or something, unless, you can save the "logged in ness" somehow

**Comment by mnovozhylov** [comment]
Hello @reedy ,

we appreciate your feedback!

Please, pay attention to the Authentication (https://developers.upwork.com/?lang=php#getting-started_authentication) section in the public documentation. It says "You need to authenticate for all requests following the OAuth 1.0, RFC 5849.". According to the specification you need to authorize the application at least once, i.e. you don't need to visit the URL every time, it's enough to configure your application once and reuse the access token as many times as you need, running the app from cron or in any other way.

P.S. Unfortunately, the mentioned PR has the lack of details. It would be great if you could share more light there. Please, provide the version of PHP and readline module you use, your environment details and how you run the application.

**Comment by reedy** [comment]
Did you read #15 which is the issue associated with the task?
