### ISSUE TITLE
Fatal error: Class 'Upwork\API\AuthTypes\MyOAuth' not found

### ISSUE THREAD

**Issue by spali90** [upwork/php-upwork#21]
Fatal error: Class 'Upwork\API\AuthTypes\MyOAuth' not found in C:\xampp\htdocs\workflow\vendor\upwork\php-upwork\src\Upwork\API\Client.php on line 55

**Comment by mnovozhylov** [comment]
Hello @spali90 ,

what configuration parameters contains your script. It seems that you specified own class which can't be found. This library doesn't use such class as "MyOAuth"
