### ISSUE TITLE
How can I change entry point to https://www.upwork.com/gds/

### ISSUE THREAD

**Issue by bischopra** [upwork/php-upwork#23]
Is there a way to change entry point from https://www.upwork.com/api/ to https://www.upwork.com/gds/?
As far as I can see use of https://www.upwork.com/api/ entry point is hard-coded.

I am trying to access:
https://developers.upwork.com/?lang=php#reports_get-earning-reports-for-a-freelancer
at present it returns only null for me (no errors or exceptions).

After enabling debug I learned that server returned '1534243642404404Wrong URL requested' and is trying to access https://www.upwork.com/api/finreports/v2/providers/{1234}/earnings.json

**Comment by mnovozhylov** [comment]
Hello @bischopra ,

you don't need to change the endpoint. You need to use the proper class and method to access Reports API. The valid endpoint will be used automatically. Please, check the documentation at https://developers.upwork.com

For instance:
```
$router = new \Upwork\API\Routers\Reports\Time($client);
$response = $router->getByFreelancerLimited('userid', array());
```

**Comment by bischopra** [comment]
Hi @mnovozhylov 

thank you for a quick response.

I did use a proper class and method as described at https://developers.upwork.com/?lang=php#reports_get-earning-reports-for-a-freelancer

Still, it does not change the fact that getByFreelancer method returns null.
This is the full debug from this method:

> \> getByFreelancer.
> \> starting GET request.
> \> running Client request, dump: Upwork\API\AuthTypes\OAuth1::__set_state(array(
> )).
> \> running request from Upwork\API\AuthTypes\OAuth1.
> \> get OAuth instance.
> \> create full url, based on global constant.
> \> url, dump: 'https://www.upwork.com/api/finreports/v2/providers/1234/earnings.json'.
> \> got response from server, dump: '
> 1534243642404404Wrong URL requested
> '.
> \> found report info, dump: NULL.

Can you advise on what to do in this case?

**Comment by mnovozhylov** [comment]
Please, 

1. make sure you use the latest version of the library
2. you initiate and use proper instance
3. you have already authenticated and authorized your application

I've just checked in the debug mode (for the already authorized app, i.e. the one that has a valid token-access pair), and it works as expected:
```
> preparing Client.
> starting Upwork\API\AuthTypes\AbstractOAuth authentication.
> authing Client.
> running auth process in Upwork\API\AuthTypes\AbstractOAuth.
> init Upwork\API\Routers\Reports\Finance\Earnings router.
> getByFreelancer.
> starting GET request.
> running Client request, dump: Upwork\API\AuthTypes\OAuth1::__set_state(array(
)).
> running request from Upwork\API\AuthTypes\OAuth1.
> get OAuth instance.
> create full url, based on global constant.
> url, dump: 'https://www.upwork.com/gds/finreports/v2/providers/1234/earnings'.
> got response from server, dump:
...
```
