### ISSUE TITLE
Use of undefined constant OAUTH_AUTH_TYPE_FORM - assumed 'OAUTH_AUTH_TYPE_FORM'

### ISSUE THREAD

**Issue by str** [upwork/php-upwork#25]
Use of undefined constant OAUTH_AUTH_TYPE_FORM - assumed 'OAUTH_AUTH_TYPE_FORM'

 (this will throw an Error in a future version of PHP)

in vendor/upwork/php-upwork/src/Upwork/API/AuthTypes/OAuth1.php line 69

**Comment by LastDragon-ru** [comment]
`AuthTypes/OAuth1` requires https://www.php.net/manual/en/book.oauth.php

**Comment by mnovozhylov** [comment]
Thank you for letting us know. We will revisit this once the future version is released, and we start supporting it. As of now, please use the versions mentioned in .travis file.

**Comment by jatinthapar1910** [comment]
This issue really needs to resolved.
