### ISSUE TITLE
Fatal error: require_once(): Failed opening required vendor/upwork/php-upwork-1.0.1/src/Upwork/API/constants.php' (include_path='.:')

### ISSUE THREAD

**Issue by qwertmax** [upwork/php-upwork#3]
Warning: require_once(vendor/upwork/php-upwork-1.0.1/src/Upwork/API/constants.php): failed to open stream: No such file or directory in vendor/autoload.php on line 2

Fatal error: require_once(): Failed opening required 'vendor/upwork/php-upwork-1.0.1/src/Upwork/API/constants.php' (include_path='.:') in vendor/autoload.php on line 2

**Comment by mnovozhylov** [comment]
Maxim, please pay attention on README file before installing a library. The library works correctly, you have neither setup, not configured it!
